//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipments
    {
        public int id_equipment { get; set; }
        public Nullable<int> id_reject { get; set; }
        public string name { get; set; }
    
        public virtual rejects rejects { get; set; }
    }
}
