//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        public materials()
        {
            this.products = new HashSet<products>();
            this.supplies_materials = new HashSet<supplies_materials>();
        }
    
        public int id_material { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public string stock_quantity { get; set; }
    
        public virtual ICollection<products> products { get; set; }
        public virtual ICollection<supplies_materials> supplies_materials { get; set; }
    }
}
