//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tipografEntities2 : DbContext
    {
        public tipografEntities2()
            : base("name=tipografEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clients> clients { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<equipments> equipments { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<order_status> order_status { get; set; }
        public DbSet<order_structures> order_structures { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<providers> providers { get; set; }
        public DbSet<rejects> rejects { get; set; }
        public DbSet<reviews> reviews { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<supplies_materials> supplies_materials { get; set; }
        public DbSet<type_products> type_products { get; set; }
        public DbSet<users> users { get; set; }
    }
}
