//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_status
    {
        public order_status()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id_order_status { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<orders> orders { get; set; }
    }
}
