//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public orders()
        {
            this.order_structures = new HashSet<order_structures>();
            this.rejects = new HashSet<rejects>();
            this.reviews = new HashSet<reviews>();
        }
    
        public int id_order { get; set; }
        public string order_number { get; set; }
        public Nullable<int> id_order_status { get; set; }
        public Nullable<int> id_clients { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string count { get; set; }
        public Nullable<int> id_employees { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual employees employees { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual ICollection<order_structures> order_structures { get; set; }
        public virtual ICollection<rejects> rejects { get; set; }
        public virtual ICollection<reviews> reviews { get; set; }
        public virtual products products { get; set; }
        public virtual users users { get; set; }
    }
}
