//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class rejects
    {
        public rejects()
        {
            this.equipments = new HashSet<equipments>();
        }
    
        public int id_reject { get; set; }
        public Nullable<int> id_orders { get; set; }
        public Nullable<int> id_products { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<equipments> equipments { get; set; }
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
