//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int id_review { get; set; }
        public Nullable<int> id_orders { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
