//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplies_materials
    {
        public int id_supplies_material { get; set; }
        public Nullable<int> id_providers { get; set; }
        public Nullable<int> id_materials { get; set; }
        public string quantity { get; set; }
        public Nullable<System.DateTime> supply_date { get; set; }
        public string cost { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual providers providers { get; set; }
    }
}
