//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_products
    {
        public type_products()
        {
            this.products = new HashSet<products>();
        }
    
        public int id_type_product { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<products> products { get; set; }
    }
}
