//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tipog
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_user { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> id_roles { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birtDay { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
